### ISSUE TITLE
[fix] 배포시 서버 오류일 때 하단 타이머 NaN 표시

### ISSUE THREAD

**Issue by darkdulgi** [softeerbootcamp4th/Team6-AwesomeOrange-FE#118]
## 어떤 상황에서 발생한 버그인가요?

> 배포 버전에서 서버 통신 오류가 나면 하단 타이머 시간이 NaN으로 표시되는 현상

## 예상 결과

> 서버 오류가 나면 타이머가 표시되지 않는다.

## 참고 이미지 및 자료
![image](https://github.com/user-attachments/assets/b65d768d-b773-45b9-a5f3-1d2094a74a8f)

**Comment by lybell-art** [comment]
해당 부분은 해결했습니다. 모든 서버 오류가 나면 오프라인 폴백 모드로 동작하게 했어요.
