### ISSUE TITLE
[feat] 어드민-이벤트등록

### ISSUE THREAD

**Issue by darkdulgi** [softeerbootcamp4th/Team6-AwesomeOrange-FE#29]
## 작업 상세 내용
- [x] 사용자는 이벤트명을 최대 40자까지 입력할 수 있다.
- [x] 이벤트명에 한글/영문/숫자/공백/특수문자 외 다른 문자가 감지되면 다르게 렌더링한다.
- [x] 사용자는 이벤트 기간을 입력할 수 있다.
- [x] 이벤트 기간 중 달력을 클릭하면, 달력 컴포넌트가 보여져서 선택할 수 있다.
- [x] 시간을 클릭하면, 시간 선택 드롭다운 컴포넌트가 보여져셔 선택할 수 있다.
- [x] 종료 시간의 경우, 시작 시간 이후에만 시간을 선택할 수 있도록 활성화한다.
- [x] 사용자는 이벤트 요약을 작성할 수 있다.
- [x] 사용자는 이벤트 url을 입력할 수 있다.
- [x] 선착순 이벤트에서, 설정한 날짜에 따라 기본으로 리스트의 선착순 이벤트 생성 아이템을 생성한다.
- [x] 상단 오픈시간, 종료시간을 설정한 후 일괄설정 버튼을 누르면, 하단 선착순 이벤트 설정 리스트의 모든 아이템의 시작시간, 종료시간이 고정된다.
- [x] 사용자는 선착순 이벤트에서 추가적으로 날짜와 시간을 설정할 수 있다.
- [x] 추첨 이벤트에서, 등수 설정을 선택할 수 있게 한다.
- [x] 등수 설정은 드롭다운으로, 최대 10등까지 구현한다.
- [x] 등수 설정에 따라, 우측 표의 보여지는 행 수가 달라진다.
- [x] 추첨 이벤트 등수 표에서 숫자를 입력할 수 있다.
- [x] 임시저장 버튼을 누르면 임시저장 api를 호출한다.
- [x] 등록 버튼을 누르면 등록 api를 호출한다.
- [ ] x 버튼을 누르거나, 화면을 종료하려고 할 경우 alert 창을 띄운다.

**Comment by lybell-art** [comment]
이벤트 등록 로직이 굉장히 복잡하고 많은 상태가 존재하기 때문에, 이 로직을 그나마 쉽게 조작할 수 있도록 리듀서까지 구현한 상태입니다.
정작 폼 자체를 추가하진 않음...
