### ISSUE TITLE
[fix] 비디오가 안 움직이는 버그

### ISSUE THREAD

**Issue by lybell-art** [softeerbootcamp4th/Team6-AwesomeOrange-FE#62]
## 어떤 버그인가요?

> 스크롤에 따라 비디오가 움직이지 않습니다.

## 어떤 상황에서 발생한 버그인가요?

> 환경 : 로컬 상황
> 환경 : MacOS 13, Chrome 127
> 상황 : 비디오를 움직이는 상황 (스크롤 인터랙션)
> 결과 : `videoRef.current.currentTime = videoTimeline`, 즉 비디오 엘리먼트의 currentTime을 변경했음에도 불구하고 currentTime이 0으로 고정되는 버그 발생

## 예상 결과

> videoRef.current.currentTime이 videoTimeline 상태로 할당됩니다.

## 참고 이미지 및 자료
<img width="1297" alt="스크린샷 2024-08-02 오전 11 11 03" src="https://github.com/user-attachments/assets/72d69d45-1499-492c-98b8-773c3ae92b60">

**Comment by lybell-art** [comment]
실제 배포된 페이지에서는 제대로 동작되는 걸 확인했습니다.
유독 제 로컬에서만 그러네요

**Comment by darkdulgi** [comment]
저도 제 자택 컴퓨터(윈10, 크롬 127)에서 dev로 호스팅하면 재생이 되지 않지만, ```npm run build```로 빌드 후 ```npm run preview```로 빌드 버전으로 호스팅하면 재생이 됩니다. vercel에서 배포된 페이지에서도 동작 되고요.
해결은 어렵지만 아마 개발버전과 빌드버전의 차이가 원인인 것 같습니다...

**Comment by lybell-art** [comment]
빌드버전에는 정상적으로 동작은 하므로 이슈 close하겠습니다.
